let people = ["Greg", "Mary", "Devon", "James"];
let removeGreg = people.shift();
console.log(people);
let addMatt = people.unshift("Matt");
console.log(people);
let removeJames = people.pop();
console.log(people);
let addMe = people.push("Ghaith");
console.log(people);
let copyList = people.slice(2);
console.log(copyList);
console.log(people.indexOf("Mary"));
console.log(people.indexOf("Foo"));
let removeMatt = people.shift();
console.log(people);
let addGreg = people.unshift("Greg");
console.log(people);
let removeMe = people.pop();
console.log(people);
let addJames = people.push("James");
console.log(people);
let AddPeople = people.splice(2, 1, `${"Elizabeth"}`, `${"Anna"}`);
console.log(people);
